name: Publish to npmjs
on:
  release:
    types: [published]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"
          
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"
          
      - run: npm ci
      - run: "npm run test"
      
      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Refresh Node-RED Library
        run: |
          curl -X POST https://flows.nodered.org/add/node \
            -H "Content-Type: application/json" \
            -d '{"id":"node-red-contrib-power-saver"}'
