name: Run tests on pull request
on: pull_request
jobs:
  build_and_test:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Oslo"
      - run: npm ci
      - run: "npm run test"
